# Generated by Django 4.1.1 on 2022-11-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('energy_kcal', models.IntegerField(default=0.0, null=True)),
                ('fat_kcal', models.IntegerField(default=0.0, null=True)),
                ('sugar', models.IntegerField(default=0.0, null=True)),
                ('picture_url', models.URLField(default='', null=True)),
            ],
        ),
    ]
