# Generated by Django 4.1.1 on 2022-11-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belly", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("age", models.IntegerField(default=0.0, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        default="male",
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
