# Generated by Django 4.1.3 on 2022-11-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
    ]
