# Generated by Django 4.1.3 on 2022-11-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belly', '0002_alter_menu_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('group', models.CharField(default='user', max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
